### ISSUE TITLE
sunshine fails

### ISSUE THREAD

**Issue by Mafeuser** [aaronbieber/sunshine.el#10]
Hi

both sunshine-forecast and sunshine-quick-forecast fail with following message:
sunshine-build-simple-forecast: Wrong type argument: listp, t

Details:
When I issue either of commands above, sunshine asks me for a login/password. I put email/password from openweathermap.org (they are for sure correct).

Then once more ask for login/password.
Then I get error mentioned above.

Why do I need to put login/password at all? http://openweathermap.org allows to see weather forecast withog giving any login.

for testing pusposes I've set:
(setq sunshine-location "90210,USA")

regards

**Comment by Mafeuser** [comment]
I forgot to mention:
vanilla emacs 24.5 on linux
regards

**Comment by aaronbieber** [comment]
Thanks for the report. OpenWeatherMap changed the way they control access to their service and so I can no longer let Sunshine pull from them anonymously. You can sign up for a free account on openweathermap.org and then click the "Hello, username" link at the top and find your API key. Enter that in the customize variable "Sunshine APPID."

Once the APPID is configured you shouldn't have to authenticate at all.

**Comment by Mafeuser** [comment]
sunshine started working.
Thanks for the help.
