### ISSUE TITLE
Does not work with Spacemacs

### ISSUE THREAD

**Issue by MrMic** [aaronbieber/sunshine.el#18]
Hi,

I got my appid key and put also sunshine-location ...
But each time I try, it asks me a Username and password!!!! And from 
New York (Can see that in the query), which is not my indicated location.
It shouldn't be like that.
Why it is not read from my spacemacs config file?

Thanks for the help and fix it.
Rgds,

**Comment by aaronbieber** [comment]
See #12 for a long discussion of the challenges in this package currently. I based this work on OpenWeatherMap's API, which has changed, and multi-day forecasts are no longer free.

Ideally it could be pivoted over to a different free service, but I don't have the time now to implement such a change. If you'd like to take a crack at it, the project is open to pull requests.
