### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by mihairinzis** [aaronbieber/sunshine.el#4]
some of us have week days translated with non ASCII characters

**Comment by aaronbieber** [comment]
I'm having trouble reproducing this because I don't know how OpenWeatherMap regionalizes their responses. Can you give me more information about your configuration?

**Comment by gour** [comment]
Here is my setup in Spacemacs:

```
;; sunshine setup
  (setq sunshine-location "Hlapičina, HR" 
        calendar-location-name "Hlapičina, HR"
        calendar-latitude 46.5178
        calendar-longitude 16.3963)
  (setq sunshine-units 'metric)
  (setq sunshine-appid "xyz")
  (setq sunshine-show-icons t)
  )
```

and Sunshine displays:

Forecast for Mursko SrediÅ¡Äe, HR

and here is city [link](http://openweathermap.org/city/3194626).

**Comment by gour** [comment]
Any progress on this one?

**Comment by aaronbieber** [comment]
I worked on it for a while but couldn't get it to work (yet). I'm still playing around with it, I can confirm that the response from OpenWeatherMap is correctly UTF-8 encoded and that it gets cached correctly on disk that way, so there must be a function somewhere in the processing that mangles the encoding.

**Comment by aaronbieber** [comment]
I've just pushed a patch that I _think_ will fix this; it fixes it for the example configuration given in this issue when I tried it. MELPA will take a while, maybe a day, to pick up the new build. If you have time, please pull the latest from here and let me know if it solves the problem.

**Comment by gour** [comment]
@aaronbieber thanks a lot for the fix. MELPA already picked it up and it works now!!
