### ISSUE TITLE
Colorscheme looks weird on default theme

### ISSUE THREAD

**Issue by leafac** [aaronbieber/sunshine.el#5]
Great work! That's exactly what I was looking for!

But the colors are not looking good on my colorscheme:

![sunshine](https://cloud.githubusercontent.com/assets/586813/5922777/4d95d314-a61c-11e4-9c7a-b2dac98caf9a.png)

You can see there's only a low contrast in the title `Forecast for Baltimore, United States of America` and the name of the days, such as `Tuesday, Jan. 27` don't even show up.

My setup is [Prelude](http://batsov.com/prelude/) with the default zenburn theme disabled by `(disable-theme 'zenburn)` as described in the documentation. I disabled it because I prefer light backgrounds.

---

On an unrelated note, please release this as a package in MELPA :smile:

**Comment by aaronbieber** [comment]
Thanks for opening this issue. I am currently using a specific named color for that heading, which is not the right thing to do. It ought to be a color keyword that will select a color from your own theme, and I had that on my mental to-do list, but it's much better as a Github issue :+1:

**Comment by leafac** [comment]
Awesome! :heart:

I'm looking forward into seeing this in MELPA :smile:

**Comment by leafac** [comment]
Hi, @aaronbieber.

I'm going to close this issue for the following reasons:
1. I'm using a dark colorscheme now and sunshine.el looks good in it.
2. sunshine.el is on MELPA.
3. It's stale.

Thanks for the project! I'm using it everyday :smile:
